# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.java.home=/home/pyrix25633/.jdks/jbr-25.0.4.1
org.gradle.configuration-cache=false

# Fabric Properties
    # check these on https://fabricmc.net/develop
    minecraft_version=26.1
    loader_version=0.18.4
    loom_version=1.17-SNAPSHOT

# Mod Properties
    semantic_version=1.6.0
    mod_version=1.6.0
    maven_group=net.rupyber_studios.fabric_tps
    archives_base_name=fabric_tps

# Dependencies
    fabric_version=0.145.1+26.1
